base_frame_id: base_link
odom_frame_id: odom
global_frame_id: map

initial_pose_x: 0.6
initial_pose_y: 0.6
initial_pose_a: 0

odom_model_type: "omni-corrected"
odom_alpha1: 0.005
odom_alpha2: 0.005
odom_alpha3: 0.01
odom_alpha4: 0.005
odom_alpha5: 0.003

min_particles: 500

kld_error: 0.05

transform_tolerance: 0.1

resample_interval: 1

laser_z_hit: 0.5
laser_z_short: 0.05
lazer_z_max: 0.05
laser_z_rand: 0.5
laser_sigma_hit: 0.2
laser_lambda_short: 0.1



update_min_d: 0.01
update_min_a: 0.01

use_map_topic: true
first_map_only: false
